/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pruebas;

import components.Tabla;
import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author diego
 */
public class Prue extends javax.swing.JFrame {

    private Tabla prov;
    
    /**
     * Creates new form Prue
     */
    public Prue() {
        initComponents();
        
        Dimension min = new Dimension(500, 600);
        this.setSize(min);
        this.getContentPane().setBackground(Color.GRAY);
        
        prov = new Tabla(properties.Constantes.PROVEEDOR);
        
        //"RIF", "Nombre", "Telefono", "Direccion"
        String[][] rows = {
                {"J-516513", "Agua Rica", "04120268754", "Sur America"},
                {"J-516510", "Agua Blanca", "04166484512", "Los Robles"},
                {"J-516671", "Rica Agua", "04241349765", "Haticos"},
                {"J-671164", "Manantial", "041231645077", "Sierra Maestra"},
                {"J-944102", "La Catedral", "04129780213", "Coromoto"},
                {"J-355177", "Agua Cristal", "04120641212", "Cumbres"},
                {"J-300187", "Monarca", "04161345216", "Varillal"},
                {"J-971230", "Agua vida", "04167980124", "Sabana Grande"},
                {"J-813218", "AquaTech", "04260132485", "San Felipe"},
        };
        
        prov.setBounds(10, 10, jPanel1.getWidth()-20, jPanel1.getHeight()-50);
        
        this.jPanel1.add(prov);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setText("Filtrar:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 380, 70, 16);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(180, 380, 300, 22);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(120, 30, 452, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        prov.buscar(jTextField1.getText());
    }//GEN-LAST:event_jTextField1KeyReleased

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prue().setVisible(true);
            }
        });
    }
    
    private void notas(){
        //        PanelFactura fac = new PanelFactura(properties.Constantes.COMPRAS);
//        fac.setSize(300, 400);
//        fac.relocateComponents();
//        
//        PanelFactura fac2 = new PanelFactura(properties.Constantes.VENTAS_BOTELLON);
//        fac2.setLocation(fac.getX()+fac.getWidth(), 0);
//        fac2.setSize(300, 450);
//        fac2.relocateComponents();
//        
//        PanelFactura fac3 = new PanelFactura(properties.Constantes.VENTAS_TRASVASO);
//        fac3.setLocation(150, fac2.getY()+fac2.getHeight());
//        fac3.setSize(300, 400);
//        fac3.relocateComponents();
//        
//        JPanel contenedor = new JPanel(null);
//        contenedor.setPreferredSize(new Dimension(1000, 1000));
//        
//        contenedor.add(fac);
//        contenedor.add(fac2);
//        contenedor.add(fac3);
//        
//        
//        JScrollPane scroll = new JScrollPane();
//        scroll.setLocation(0, 0);
//        scroll.setSize(min);
//        scroll.setViewportView(contenedor);
//        
//        this.add(scroll);
        
//        GridLayout grid = new GridLayout(2, 5);
//        grid.setHgap(10);
//        grid.setVgap(10);
//        this.setLayout(grid);
//        
//        this.addComponentListener(new ComponentAdapter() {
//            @Override
//            public void componentResized(ComponentEvent e) {
//                int width = getWidth();
//                
//                System.out.println(width);
//                
//                if(width < 500){
//                    grid.setColumns(2);
//                    grid.setRows(5);
//                } else if(width < 700){
//                    grid.setColumns(3);
//                    grid.setRows(4);
//                    
//                } else if(width < 900){
//                    grid.setColumns(4);
//                    grid.setRows(3);
//                } else {
//                    grid.setColumns(5);
//                    grid.setRows(2);
//                }
//                
//                System.out.println("row = "+grid.getRows()+" col = "+grid.getColumns());
//                setLayout(grid);
//                
//                revalidate();
//                repaint();
//            }
//        });
//        
//        JButton btn1 = new JButton("boton 1");
//        JButton btn2 = new JButton("boton 2");
//        JButton btn3 = new JButton("boton 3");
//        JButton btn4 = new JButton("boton 4");
//        JButton btn5 = new JButton("boton 5");
//        JButton btn6 = new JButton("boton 6");
//        JButton btn7 = new JButton("boton 7");
//        JButton btn8 = new JButton("boton 8");
//        JButton btn9 = new JButton("boton 9");
//        JButton btn10 = new JButton("boton 10");
//        
//        this.add(btn1);
//        this.add(btn2);
//        this.add(btn3);
//        this.add(btn4);
//        this.add(btn5);
//        this.add(btn6);
//        this.add(btn7);
//        this.add(btn8);
//        this.add(btn9);
//        this.add(btn10);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
